base:
  path:
    data: "/shared/mydata.csv"
    logs: "logs"
    log_config: "adv_ds_logging.yml"
  rf_params:
    n_estimators: 400

dev:
  path_db: "sqlite:////some_dir/dev.db"
  
prod:
  path_db: "sqlite:////some_other_dir/prod.db"


train:
  col_label: "SalePrice"
  cols_to_ignore: []
  numerical_columns: [
    'MSSubClass',
    'OverallQual',
    'OverallCond',
    '1stFlrSF',
    'GrLivArea',
    'BsmtFullBath',
    'Fireplaces',
    'GarageCars',
    'LotFrontage'
    ]
  categorical_columns: [
    'MSZoning',
    'Neighborhood',
    'RoofStyle',
    'MasVnrType',
    'BsmtQual',
    'BsmtExposure',
    'HeatingQC',
    'CentralAir',
    'KitchenQual',
    'FireplaceQu',
    'GarageType',
    'GarageFinish',
    'PavedDrive'
                      ]
  algorithm_module: "sklearn.linear_model"
  algorithm_name: "Lasso"
  algorithm_params:
    alpha: 0.005
    random_state: 42